import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import { Suspense } from "react";
import Providers from "@/app/providers";
import ProgressBar from "@/components/nprogress";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${jetBrainsMono.variable} antialiased selection:bg-violet-500/15 selection:text-violet-400 min-h-screen flex flex-col`}
      >
        <Providers>
          <Suspense fallback={null}>
            <ProgressBar />
          </Suspense>
          {children}
        </Providers>
      </body>
    </html>
  );
}
