import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import Providers from "@/app/providers";
import ProgressBar from "@/components/nprogress";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased selection:bg-teal-500/20 selection:text-teal-300`}>
        <Providers>
          <Suspense fallback={null}>
            <ProgressBar />
          </Suspense>
          {children}
        </Providers>
      </body>
    </html>
  );
}
